[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "voxel"
authors = [
    { name = "Micah Woodard", email = "micah.woodard@alleninstitute.org" },
    { name = "Adam Glaser", email = "adam.glaser@alleninstitute.org" },
    { name = "Walter Mwaniki", email = "walter.mwaniki@alleninstitute.org" },
]
version = "0.0.0"
dynamic = ["description"]
description-file = 'README.md'
dependencies = [
    'pyserial >= 3.5',
    'ruamel-yaml >= 0.18.5',
    'psutil >= 5.9.8',
    'nidaqmx >= 0.9.0',
    'matplotlib >= 3.8.2',
    'scipy >= 1.12.0',
    'PyImarisWriter >= 0.7.0',
    'tifffile >= 2024.1.30',
    'egrabber >= 0.0.2',
    'h5py >= 3.0.0',
    'scikit-image >= 0.20.0',
    'gputools >= 0.2.14',
    'scikit-tensor-py3',
    'tensorstore >= 0.1.56',
    'pyclesperanto >= 0.8.2',
    'pylablib >= 1.4.2',
    'pytest >= 8.2.1',
    'inflection >= 0.5.1',
    'tigerasi >= 0.0.26',
    'pydantic >= 2.7.3',
    'PyVISA >= 1.14.1',
    'PyVISA-py >= 0.7.2',
    'pyusb >= 1.2.1',
    'imohash >= 1.0.5',
    'sympy >= 1.12.1',
    'pycobolt @ git+https://github.com/cobolt-lasers/pycobolt.git',
    'histogram1d >= 0.14',
]
